# Generated by Django 6.0.3 on 2026-03-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy_app', '0002_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='consentrecord',
            options={'ordering': ['-date_submitted']},
        ),
        migrations.AlterModelOptions(
            name='databreachreport',
            options={'ordering': ['-date_reported']},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databreachreport',
            name='affected_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='databreachreport',
            name='title',
            field=models.CharField(default='No Title', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
